# Generated by Django 3.1.7 on 2021-11-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InqMessage',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('channel_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('create_at', models.CharField(max_length=64)),
            ],
        ),
    ]
