# Generated by Django 3.1.7 on 2021-11-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inqmessage',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
