# Generated by Django 3.1.7 on 2021-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211113_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='InqChannels',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InqChannelToUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
            ],
        ),
    ]
